#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  limitSwitch1,   sensorTouch)
#pragma config(Sensor, dgtl2,  limitSwtich2,   sensorTouch)
#pragma config(Sensor, dgtl3,  limitSwitch3,   sensorTouch)
#pragma config(Sensor, dgtl11, encoderVal,     sensorQuadEncoder)
#pragma config(Motor,  port9,           liftM,         tmotorVex393_MC29, openLoop, encoderPort, dgtl11)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int speed = 25;
int numberOfTicks = -200;
int lineVal = 2850;
task main()
{
	SensorValue[lineFollower] = 0;
//goal is to move for 3 seconds at half speed.
while(SensorValue[lineFollower] > lineVal)
	{
		motor[liftM] = -speed;
	}
	motor[liftM] = 0;
}
