#pragma config(Sensor, dgtl12, button,         sensorTouch)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//make function to go straight
void goForward(int leftSpeed, int rightSpeed, int time )
{
	motor[leftMotor] = (int)-leftSpeed;
	motor[rightMotor] = (int)-rightSpeed;
	wait1Msec(time);
}//end of goForward function

//make function to go back
void goBack(int leftSpeed, int rightSpeed, int time )
{
	motor[leftMotor] = (int)leftSpeed;
	motor[rightMotor] = (int)rightSpeed;
	wait1Msec(time);
}//end of goBack function

void goLeft(int leftSpeed, int rightSpeed, int time )
{
	motor[leftMotor] = leftSpeed;
	motor[rightMotor] = rightSpeed;
	wait1Msec(time);
}//end of goLeft function

void goRight(int leftSpeed, int rightSpeed, int time)
{
	motor[leftMotor] = leftSpeed; //(8)
	motor[rightMotor] = rightSpeed; // (16)
	wait1Msec(time);
}

task main()
{
	while (SensorValue[button] == 0) {
		motor[leftMotor] = -55;
		motor[rightMotor] = -55;
		wait1Msec(1);
}
while(SensorValue[button] == 1) {
	motor[leftMotor] = 0;
		motor[rightMotor] = 0;
		wait1Msec(1000);
}

}//end of task main()
