#pragma config(Sensor, in2,    marbleLineFollower, sensorLineFollower)
#pragma config(Motor,  port1,           cupServo,      tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port3,           marbleIntake,  tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int yellowAndrew = 50;  //This is the marble name and value for when the line follower sees a clear marble
int blueBilly = 100;  //This is the marble name and value for when the line follower sees a blue marble
int blackBruce = 200;  //This is the marble name and value for when the line follower sees a wooden marble

void moveQuarterly()
{
	motor[cupServo] = 25; //This function causes the cup holding servo to move towards the Andrew cup
}

void moveHalf()
{
	motor[cupServo]= 50; //This function causes the cup holding servo to move towards the Billy cup
}

void moveFull()
{
	motor[cupServo] = 127; //This function causes the cup holding servo to move towards the Bruce cup
}

task main()
{
	//When the line follower encounters a marble it will move cups with the help of a servo
	if	(SensorValue[marbleLineFollower] > yellowAndrew)
	{
		moveFull(); //After its value is read by the Light sensor the clear marble will fall into the correct cup
	}
	if	(SensorValue[marbleLineFollower]  >blueBilly)
	{
		moveHalf(); //After its value is read by the Light sensor the blue marble will fall into the correct cup
	}
	if	(SensorValue[marbleLineFollower] > blackBruce)
	{
		moveQuarterly();	//After its value is read by the Light sensor the wodden marble will fall into the correct cup
	}
}
