#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  limitSwitch1,   sensorTouch)
#pragma config(Sensor, dgtl2,  limitSwtich2,   sensorTouch)
#pragma config(Sensor, dgtl3,  limitSwitch3,   sensorTouch)
#pragma config(Sensor, dgtl11, encoderVal,     sensorQuadEncoder)
#pragma config(Motor,  port9,           liftM,         tmotorVex393_MC29, openLoop, encoderPort, dgtl11)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int speed = 50;
int pressed = 1;
int floor2 = -301;
bool hasReached2ndFloor;
task main()
{
//Must begin at floor one, at any given level it must move down to level 1
if(SensorValue[lineFollower] > 2700)
{
	while(SensorValue[encoderVal] > 5)
	{
		motor[liftM] = -speed;
	}
		motor[liftM] = 0;
}

	SensorValue[encoderVal] = 0;
	while(true){
/*CREATE A "DO-NOTHING" FUNCTION
	When you're on the first floor of an elevator, and you press level 1, it won't move
*/
if(SensorValue(limitSwtich2) == pressed)//GO TO 2ND FLOOR
{
	clearTimer(T1);

	//run to bottom position
	 while(SensorValue[encoderVal] > floor2)
  {
    motor[liftM] = speed;
    hasReached2ndFloor = true;
  }
  motor[liftM] = 0;
}

}//end of if

if(SensorValue(limitSwitch3) == pressed)
{
//end of while

}//end of "class"

}
