#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  limitSwitch1,   sensorTouch)
#pragma config(Sensor, dgtl2,  limitSwtich2,   sensorTouch)
#pragma config(Sensor, dgtl3,  limitSwitch3,   sensorTouch)
#pragma config(Sensor, dgtl11, encoderVal,     sensorQuadEncoder)
#pragma config(Motor,  port9,           liftM,         tmotorVex393_MC29, openLoop, encoderPort, dgtl11)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int speed = 50;
int pressed = 1;
int tickLvl2 = -200;
int tickLvl3 = -200;
task main()
{
	SensorValue[encoderVal] = 0;
	while(1==1){
		if(time1[T1] == 3000)
	{
	//run to bottom positon
	}//end of if

if(SensorValue(limitSwitch1) == pressed)
{
	clearTimer(T1);
	//run to bottom position
	 while(SensorValue[encoderVal] > tickLvl3)
  {
    motor[liftM] = speed;
  }
  motor[liftM] = 0;
}

}//end of if
if(SensorValue(limitSwtich2) == 1)
{
clearTimer(T1);
//run to middle position
while(SensorValue[encoderVal] < tickLvl2)
  {
    motor[liftM] = speed;
  }
  motor[liftM] = 0;
}//end of if
if(SensorValue(limitSwitch3) == pressed)
{
//end of while

}//end of "class"

}
